WITH CATEGORY_TOTAL_PRICE AS( 
    SELECT CATE_ID, SUM(PRICE) as 'TOTAL_PRICE' FROM SHOPPING_BASKET_PRODUCTS
    GROUP BY CATE_ID)

SELECT SHOPPING_BASKET.USER_ID, COUNT(SHOPPING_BASKET.USER_ID) as count_user_id, SUM(CATEGORY_TOTAL_PRICE.TOTAL_PRICE) as total_price FROM SHOPPING_BASKET
INNER JOIN CATEGORY_TOTAL_PRICE
ON SHOPPING_BASKET.CATEGORY_ID = CATEGORY_TOTAL_PRICE.CATE_ID
GROUP BY SHOPPING_BASKET.USER_ID;